name: crimson
description: Fast, efficient and easy-to-use JSON parser and serializer for Dart.
repository: https://github.com/simc/crimson
version: 0.3.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^4.0.0
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master
