name: crimson_test
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crimson:
    path: ../
  intl: ^0.19.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  test: ^1.25.8
  freezed_annotation: ^2.4.4
  dart_json_mapper: ^2.2.14
  freezed: ^2.5.7
